### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by firwer** [UPetit/python-binance-profit#15]
Hello there, hope you could update the documentation for the usage of market order and buying by % of wallet balance. That would be extremely helpful! Thank you!

**Comment by UPetit** [comment]
Hey 👋
Absolutely! I've added both of them #5 and #6 last week in the issues section.
I'll start with the market order as the function is already defined in the code and then I'll work on the % of wallet balance feature.
I'll do my changes in the dev branch first and I'll keep you updated.
Thanks

**Comment by UPetit** [comment]
Hi @firwer,
I've pushed some changes on [dev branch](../tree/dev) to support the market buy order in the strategy.
You'll find the instructions in the README on the same branch. This is ready to test!
Don't hesitate if you have any question / issue.
I'll work on the feature to use the % of wallet later in the week.

**Comment by firwer** [comment]
> Hi @firwer,
> I've pushed some changes on [dev branch](../tree/dev) to support the market buy order in the strategy.
> You'll find the instructions in the README on the same branch. This is ready to test!
> Don't hesitate if you have any question / issue.
> I'll work on the feature to use the % of wallet later in the week.

Great! Thanks for the effort
