### ISSUE TITLE
issue OCO

### ISSUE THREAD

**Issue by seanjeanc** [UPetit/python-binance-profit#27]
Hi!

Thanks for the work put into this. I am following instructions in your readme file.

I am buying at market price, but I get this error sometimes, but not all the time. Not sure what the issue could be.

 
  File "/home/user/python-binance-profit/app/client.py", line 424, in execute_sell_strategy
    oco_order = OCOOrder(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for OCOOrder
__root__
  The price is not valid compared to current avg trades. (type=value_error)
__root__
  The price is not valid compared to current avg trades. (type=value_error)

I have tried selling my spot position and starting all over again, but same error.

**Comment by UPetit** [comment]
Hi @seanjeanc,

It seems like the calculated selling prices are off-limit as per [Binance rule](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#percent_price).

At this [line](https://github.com/UPetit/python-binance-profit/blob/985b3dd2ec97f753b795519f571da7bc73c740c8/app/object_values/orders.py#L77) each price calculated (profit price and the stop loss price) is checked against the Binance rule: they should stay between a certain range based on the average price of the recent trades.

Could you please tell me what were your parameters when you ran the script? What profit and loss % did you select?

**Comment by seanjeanc** [comment]
Thanks for replying,

Issue is not happening anymore. Strange.

Will re-open issue if I see it happening again!
