### ISSUE TITLE
Featurerequest, have OCO orders not be limit, but market orders

### ISSUE THREAD

**Issue by joengelh** [UPetit/python-binance-profit#28]
today a stop loss was not executed, since the price of BNB to FL fell too fast. 
Could the OCO orders be changed to be market orders instead of limit orders, so sl is guaranteed even if the price falls fast? 

Thanks a lot

**Comment by UPetit** [comment]
Hi @joengelh,

Indeed, this is a known issue. Adding a stop price parameter that is different from the stop limit will help (at the moment in the script `stop limit` = `stop price`).
This is a future enhancement that is planned: #3.
I'm quite busy at the moment but I will have look asap 🙏 
I'm closing this one to keep the first ticket opened.

Thanks.
