### ISSUE TITLE
Add buy market order choice

### ISSUE THREAD

**Issue by UPetit** [UPetit/python-binance-profit#5]
Add the possibility to choose between the buy limit order or the buy market order

Idea: `--price` with an empty value could mean a market order for instance ?

**Comment by JulienDev** [comment]
Or maybe --market ?

**Comment by UPetit** [comment]
Definitely better 👍 Thanks!

**Comment by UPetit** [comment]
The [dev branch](../tree/dev) has been updated to support the market buy order using the argument `--buy_type market`. All the information or in the README of the same branch.
