### ISSUE TITLE
[BUG] Order does not exist

### ISSUE THREAD

**Issue by UPetit** [UPetit/python-binance-profit#8]
**Describe the bug**
When the buy order has been executed, it's sometimes not possible to fetch the order (due to Binance network maybe?) and the API returns: `binance.exceptions.BinanceAPIException: APIError(code=-2013): Order does not exist.`

**To Reproduce**
Run the scripe execute_orders.py

**Expected behavior**
The buy order should be fetched using the order id previously stored.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OS Catalina
 - Python version: 3.7.4
 - Release version: v0.0.1

**Additional context**

**Comment by UPetit** [comment]
Adding few retries should work for both this issue and #1

**Comment by UPetit** [comment]
Fixed in last commits

**Comment by sumade123** [comment]
I got this bug today - any idea what could have caused it? 

From your comment it seems the commit added the capacity to retry to the library. Do I need to retry within my own code? 
I suppose if after 3 retries it does not work this error will still be produced?

There was a lot of trading activity today, so it seems this might be the reason - but I am not sure how to best avoid the issue.
